In [ ]:
''' 
y_pred = 推理函数
a = 学习率

——————————推理函数y_pred——————————
设
w = [w0,w1] (权重向量)
x = [1,x1] (特征向量 x0 = 1 代表截距)

y = wx =  w0*1 + w1*x1

推理函数
y_pred = y


——————————损失函数L——————————
y = 标签
二次方距离作为损失函数
L = (y_pred - y)^2


——————————损失函数对于w的偏导数dL——————————
令u = (y_pred - y)
dL/dw 
= 2u * u'
2u = 2(y_pred - y)
u' = (wx - y)' = x

则
dL/dw = 2(y_pred - y) * x


——————————更新权重——————————
w = w - a * dL

'''

In [ ]:
'''   
1 梯度下降 
所有样本计算 dL/dw 后 更新

2 随机梯度下降
单个样本计算 dL/dw 后 更新

3 正规方程
损失函数是一个二次函数 
因此最小值在 dL/dw = 0 处

2(y_pred - y) * x = 0 
2(wx - y) * x = 0 
x^2w = xy
w = (x^2)^-1 * xy
'''

In [10]:
import numpy as np
class LinearRegression:
    def __init__(self, l_rate=0.01, n_iterations=1000, method="GD"):
        self.l_rate = 0.01 # 学习率
        self.n_iterations = 1000 # 迭代次数
        self.method = "GD" # 默认的优化方法
        self.w = None # 权重


    def fit(self, x, y):
        ''' 
        最左增加一列 1 作为截距项
        x = [x1, x2, x3] -> [1, x1, x2, x3]

        x.shape = (m,n)
        m = 样本数
        n = 特征数 (包含增加的偏置项)
        '''
        x = np.concatenate([np.ones((x.shape[0],1)),x],axis=1)
        m, n = x.shape 
        y = y.reshape(-1,1) # 确保形状为(m,1)


        if self.method == 'GD': # 梯度下降 算完了一次性更新权重
            self.w = np.zeros((n,1)) # 初始化权重
            for i in range(self.n_iterations):
                ''' 
                推理函数 y_pred = wx
                损失函数 L = (y_pred - y)^2
                损失函数对w的偏导数 dL = 2x(y_pred - y)
                更新权重 w = w - l_rate * dL
                '''
                y_pred = x @ self.w 
                dL = 2 * x.T @ (y_pred - y) / m # 除以m求均值
                self.w = self.w - self.l_rate * dL 

        elif self.method == 'SGD': # 随机梯度下降 每次都更新权重
            self.w = np.zeros((n,1)) # 初始化权重
            for i in range(self.n_iterations):
                # 随机选择一个样本
                id = np.random.randint(m) 
                xi = x[id:id+1]
                yi = y[id:id+1]

                ''' 
                推理函数 y_pred = wx
                损失函数 L = (y_pred - y)^2
                损失函数对w的偏导数 dL = 2x(y_pred - y)
                更新权重 w = w - l_rate * dL
                '''
                y_pred = xi @ self.w 
                dL = 2 * xi.T @ (y_pred - yi) 
                self.w = self.w - self.l_rate * dL 

        elif self.method == 'NormalEquation': # 正规方程 数据的解析解
            self.w = np.linalg.inv(x.T @ x) @ x.T @ y # w = (x^2)^-1 * xy


    def predict(self,x):
        x = np.concatenate([np.ones((x.shape[0],1)),x],axis=1)
        return x @ self.w

In [11]:
# 使用模型

# 创建数据集
np.random.seed(42)
x = np.array([[1], [2], [3], [4], [5]])  # 特征：1维，5个样本
y = np.array([3, 5, 7, 9, 11])  # 标签：y = 2*x + 1 加少量噪声

print("使用数据:")
print(f"x: {x.flatten()}")
print(f"y: {y}")
print('数据规律 y = 2x + 1')



# 实例化 梯度下降
model = LinearRegression(l_rate=0.01, n_iterations=100, method="GD")
model.fit(x, y) # 训练
y_pred = model.predict(x) # 用训练数据预测
print(y_pred.flatten())  # 展平为1维数组


# 实例化 随机梯度下降
model = LinearRegression(l_rate=0.01, n_iterations=100, method="SGD")
model.fit(x, y) # 训练
y_pred = model.predict(x) # 用训练数据预测
print(y_pred.flatten())  # 展平为1维数组

# 实例化 正规方程
model = LinearRegression(l_rate=0.01, n_iterations=100, method="NormalEquation")
model.fit(x, y) # 训练
y_pred = model.predict(x) # 用训练数据预测
print(y_pred.flatten())  # 展平为1维数组

使用数据:
x: [1 2 3 4 5]
y: [ 3  5  7  9 11]
数据规律 y = 2x + 1
[ 2.98987045  4.99375103  6.99763161  9.0015122  11.00539278]
[ 2.98987045  4.99375103  6.99763161  9.0015122  11.00539278]
[ 2.98987045  4.99375103  6.99763161  9.0015122  11.00539278]
